<a href="https://colab.research.google.com/github/Lavan1999/100-Dataset-6---Shopping-Dataset-/blob/main/ShoppingDataAnalysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
from scipy import stats

In [10]:
df = pd.read_csv("/content/Shopping_data.csv")
df

     CustomerID   Genre  Age  Annual Income (k$)  Spending Score (1-100)
0             1    Male   19                  15                      39
1             2    Male   21                  15                      81
2             3  Female   20                  16                       6
3             4  Female   23                  16                      77
4             5  Female   31                  17                      40
..          ...     ...  ...                 ...                     ...
195         196  Female   35                 120                      79
196         197  Female   45                 126                      28
197         198    Male   32                 126                      74
198         199    Male   32                 137                      18
199         200    Male   30                 137                      83

[200 rows x 5 columns]

In [5]:
df["Annual Income (k$)"].unique()

array([ 15,  16,  17,  18,  19,  20,  21,  23,  24,  25,  28,  29,  30,
        33,  34,  37,  38,  39,  40,  42,  43,  44,  46,  47,  48,  49,
        50,  54,  57,  58,  59,  60,  61,  62,  63,  64,  65,  67,  69,
        70,  71,  72,  73,  74,  75,  76,  77,  78,  79,  81,  85,  86,
        87,  88,  93,  97,  98,  99, 101, 103, 113, 120, 126, 137])

In [ ]:
'''
1---Unsupervised Data


2--- Category Column - "Genre"
 --- Continuous column - "CustomerID", "Annual Income (k$)", "Spending Score (1-100)","Age"

3---Correlation Test for Numerical columns

4--- Hypothesis testing: continuous Vs continuous
      customerid-annual income
      customerid-spendingscore
      customerid-age
      annualincome-spendingscore
      annualincome-age
      spendingscore-age
5---Hypothesis testing for category VS continous
      genre vs customerid
      genre vs annual income
      genre vs spending score
      genre vs age

In [ ]:
#Correlation Test for Numerical Columns


'''

df.corr()
By the result of correlation Test,
No related columns -    customer id with age,
                        customer id with spending score,
                        annual income with age,
                        spending score with annual income

# Related columns - costomer id and annual income,
                    age and spending score,'''

In [24]:
df.corr()

<ipython-input-24-2f6f6606aa2c>:1: FutureWarning: The default value of numeric_only in DataFrame.corr is deprecated. In a future version, it will default to False. Select only valid columns or specify the value of numeric_only to silence this warning.
  df.corr()

,CustomerID,Age,Annual Income (k$),Spending Score (1-100)
CustomerID,1.000000,-0.026763,0.977548,0.013835
Age,-0.026763,1.000000,-0.012398,-0.327227
Annual Income (k$),0.977548,-0.012398,1.000000,0.009903
Spending Score (1-100),0.013835,-0.327227,0.009903,1.000000

In [ ]:
'''customerid-annual income
                                   customerid-annual income
                                   customerid-spendingscore
                                   customerid-age
                                   annualincome-spendingscore
                                   annualincome-age
                                   spendingscore-age '''

In [ ]:
#Hypothesis Testing

#1-Two sample ttest for CustomerID VS spendinscore

for i in range(40):
  sample1 = df.CustomerID.sample(frac=0.05)
  sample2 = df["Spending Score (1-100)"].sample(frac=0.04)

  t_test, p_value = stats.ttest_ind(sample1,sample2)
  if p_value > 0.05:
    print("H0 null hypothesis accepted and Ha alternative hypothesis rejected")
  else:
    print("H0 null hypothesis rejected and Ha alternative hypothesis accepted")

# Here I got 17 acceptance and 23 rejection so that Null hypothesis is rejected by the majaricy results

In [ ]:
#Hypothesis Testing

#1-Two sample ttest for CustomerID VS age

for i in range(40):
  sample1 = df.CustomerID.sample(frac=0.05)
  sample2 = df["Age"].sample(frac=0.04)

  t_test, p_value = stats.ttest_ind(sample1,sample2)
  if p_value > 0.05:
    print("H0 null hypothesis accepted and Ha alternative hypothesis rejected")
  else:
    print("H0 null hypothesis rejected and Ha alternative hypothesis accepted")

# Here I got 8 acceptance and 32 rejection so that Null hypothesis is rejected by the majaricy results

In [ ]:
#Hypothesis Testing

#1-Two sample ttest for CustomerID VS annual income

for i in range(40):
  sample1 = df.CustomerID.sample(frac=0.05)
  sample2 = df["Annual Income (k$)"].sample(frac=0.04)

  t_test, p_value = stats.ttest_ind(sample1,sample2)
  if p_value > 0.05:
    print("H0 null hypothesis accepted and Ha alternative hypothesis rejected")
  else:
    print("H0 null hypothesis rejected and Ha alternative hypothesis accepted")

# Here I got 23 acceptance and 17 rejection so that Null hypothesis is accepted by the majaricy results

In [ ]:
#Hypothesis Testing

#1-Two sample ttest for annual income VS spendinscore

for i in range(40):
  sample1 = df["Spending Score (1-100)"].sample(frac=0.05)
  sample2 = df["Annual Income (k$)"].sample(frac=0.04)

  t_test, p_value = stats.ttest_ind(sample1,sample2)
  if p_value > 0.05:
    print("H0 null hypothesis accepted and Ha alternative hypothesis rejected")
  else:
    print("H0 null hypothesis rejected and Ha alternative hypothesis accepted")

# Here I got 42 acceptance and 8 rejection so that Null hypothesis is accepted by the majaricy results

In [ ]:
#Hypothesis Testing

#1-Two sample ttest for annualincome - age

for i in range(40):
  sample1 = df["Age"].sample(frac=0.05)
  sample2 = df["Annual Income (k$)"].sample(frac=0.04)

  t_test, p_value = stats.ttest_ind(sample1,sample2)
  if p_value > 0.05:
    print("H0 null hypothesis accepted and Ha alternative hypothesis rejected")
  else:
    print("H0 null hypothesis rejected and Ha alternative hypothesis accepted")

# Here I got 17 acceptance and 23 rejection so that Null hypothesis is rejected by the majaricy results

In [ ]:
#Hypothesis Testing

#1-Two sample ttest for annual age VS spendinscore

for i in range(40):
  sample1 = df["Spending Score (1-100)"].sample(frac=0.05)
  sample2 = df["Age"].sample(frac=0.04)

  t_test, p_value = stats.ttest_ind(sample1,sample2)
  if p_value > 0.05:
    print("H0 null hypothesis accepted and Ha alternative hypothesis rejected")
  else:
    print("H0 null hypothesis rejected and Ha alternative hypothesis accepted")

# Here I got 42 acceptance and 8 rejection so that Null hypothesis is accepted by the majaricy results

In [20]:
# f-Test for continuous vs category

group = df['Genre'].unique()
data = {}
for i in group:
  data[i]=df["Annual Income (k$)"][df["Genre"]==i]


f_value, p_value = stats.f_oneway(data['Male'],data['Female']
                                  )
print(f_value, p_value)
if p_value<0.05:
  print("H0 - Null hypothesis is rejected which means no relationship exists")
else:
  print("Ha - Null hypothesis is accepted which means relationship exists")
#Result --Ha - Null hypothesis is accepted which means relationship exists

0.6320604552747227 0.4275524939992865
Ha - Null hypothesis is accepted which means relationship exists

In [21]:
# f-Test for continuous vs category

group = df['Genre'].unique()
data = {}
for i in group:
  data[i]=df["Age"][df["Genre"]==i]


f_value, p_value = stats.f_oneway(data['Male'],data['Female'])

print(f_value, p_value)
if p_value<0.05:
  print("H0 - Null hypothesis is rejected which means no relationship exists")
else:
  print("Ha - Null hypothesis is accepted which means relationship exists")
#Result --Ha - Null hypothesis is accepted which means relationship exists

0.7362859039559835 0.39189073778826133
Ha - Null hypothesis is accepted which means relationship exists

In [22]:
# f-Test for continuous vs category

group = df['Genre'].unique()
data = {}
for i in group:
  data[i]=df["Spending Score (1-100)"][df["Genre"]==i]


f_value, p_value = stats.f_oneway(data['Male'],data['Female'])

print(f_value, p_value)
if p_value<0.05:
  print("H0 - Null hypothesis is rejected which means no relationship exists")
else:
  print("Ha - Null hypothesis is accepted which means relationship exists")
#Result --Ha - Null hypothesis is accepted which means relationship exists

0.6708370300325192 0.4137446589852207
Ha - Null hypothesis is accepted which means relationship exists

In [23]:
# f-Test for continuous vs category

group = df['Genre'].unique()
data = {}
for i in group:
  data[i]=df["CustomerID"][df["Genre"]==i]


f_value, p_value = stats.f_oneway(data['Male'],data['Female'])

print(f_value, p_value)
if p_value<0.05:
  print("H0 - Null hypothesis is rejected which means no relationship exists")
else:
  print("Ha - Null hypothesis is accepted which means relationship exists")
#Result --Ha - Null hypothesis is accepted which means relationship exists

0.6545180987538248 0.4194730348538205
Ha - Null hypothesis is accepted which means relationship exists